apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ticketing.dev
      http:
        paths:
         - path: /api/users/currentuser
           pathType: Prefix
           backend:
             service:
               name: auth-clusterip-srvs
               port:
                 number: 3000
         - path: /api/users/signup
           pathType: Prefix
           backend:
             service:
               name: auth-clusterip-srvs
               port:
                 number: 3000
         - path: /api/users/signin
           pathType: Prefix
           backend:
             service:
               name: auth-clusterip-srvs
               port:
                 number: 3000
         - path: /api/users/signout
           pathType: Prefix
           backend:
             service:
               name: auth-clusterip-srvs
               port:
                 number: 3000
                 