apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: soufiane12345/payment:latest
          env:
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-clusterip-srvs:4222
            - name: MONGO_URI
              value: "mongodb://payment-mongo-clusterip-srvs:27017/payment"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-sercret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: payment-clusterip-srvs
spec:
  selector:
    app: payment
  type: ClusterIP
  ports:
    - name: payment
      protocol: TCP
      port: 3000
      targetPort: 3000